services:
  - type: web
    name: nextalk-server
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: CLIENT_ORIGIN
        sync: false
    autoDeploy: true
    plan: free
    healthCheckPath: /
